import './globals.css'

import { GoogleTagManager } from '@next/third-parties/google'
import type { Metadata } from 'next'
import localFont from 'next/font/local'
import { ReactNode } from 'react'

import { AppSidebar } from '@/components/AppSidebar'
import { ThemeProvider } from '@/components/ThemeProvider'
import { SidebarProvider, SidebarTrigger } from '@/components/ui/sidebar'

import Providers from './providers'
import StoreProvider from './StoreProvider'

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
})
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
})

export const metadata: Metadata = {
  title: 'My App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <GoogleTagManager gtmId="GTM-TJJBHMC5" />
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Providers>
            <StoreProvider>
              <SidebarProvider>
                <AppSidebar />
                <main className="flex w-full flex-1 flex-col">
                  <SidebarTrigger />
                  {children}
                </main>
              </SidebarProvider>
            </StoreProvider>
          </Providers>
        </ThemeProvider>
      </body>
    </html>
  )
}
